= IoT Agents

Actual IoT devices are simulated in the lab via an *IoT Agent* a small piece of software that will provide the inteface for real or simulated devices to interact with the smart village platform.

An IoT Agent receives messages from smart devices to update the device state, or perform some kind of action on the device. The IoT Agent is a reactive application that can:

* register smart devices
* connect to various types of message brokers
* receive messages in a native device protocol
* and send updates to a context broker following the NGSI-LD standard format for smart device data.

You can find the full [NGSI-LD API Operation Definition in section 5 of this PDF]. NGSI-LD stores entities as the primary data stored. Entities can be any data representing any [Smart Device Model data](https://github.com/smart-data-models) in the world. There are so many Smart Data Models in the world, but they can be grouped into the following domains:

* Smart Cities
* Smart Agrifood
* Smart Water
* Smart Energy
* Smart Logistics
* Smart Robotics
* Smart Sensoring
* Cross sector
* Smart Health
* Smart Destination
* Smart Environment
* Smart Aeronautics
* Smart Manufacturing
* Incubated
* Harmonization

Don't feel limited to stick to these domains, you can create your own smart data models and follow the NGSI-LD specification to confirm to all the latest open standards for managing smart device data. Here are some of the native device protocols and corresponding IoT Agents that can connect the device to the context broker. 

- link:https://fiware-iotagent-json.readthedocs.io/en/latest/[IoTAgent-JSON] - a bridge between HTTP/MQTT messaging (with a JSON payload) and NGSI
- link:https://fiware-iotagent-lwm2m.readthedocs.io/en/latest[IoTAgent-LWM2M] - a bridge between the Lightweight M2M protocol and NGSI
- link:https://fiware-iotagent-ul.readthedocs.io/en/latest[IoTAgent-UL] - a bridge between HTTP/MQTT messaging (with an UltraLight2.0 payload) and NGSI
- link:https://fiware-lorawan.readthedocs.io/en/latest[IoTAgent-LoRaWAN] - a bridge between the LoRaWAN protocol and NGSI
- link:https://iotagent-opcua.readthedocs.io/en/latest/[IoTagent-OPCUA] - a bridge between the OPC-UA protocol and NGSI

== The Smart Village IoT Agent

If you are curious what the IoTAgentJson custom resource definition looks like that we are using, run the command below in your workbench terminal:

----
cat ~/smartvillage-operator/kustomize/overlays/sandbox/iotagentjsons/iotagent-json/iotagentjson.yaml
echo DONE
----

Here are some useful things to note about the configuration of the IoT Agent JSON: 

* `ngsild:` We configure the host and port of the context broker, we use the ScorpioBroker host and port in the same namespace.

* `mongodb:` We configure the name of MongoDB, and the kubernetes Secret name and key for the MongoDB password. This allows us to connect to MongoDB to store smart device registrations.

* `message_broker:` We configure the host of the message broker, and the kubernetes Secret name and key for the RabbitMQ password. This allows us to connect to RabbitMQ and start listening for messages. 

* `replicas: 1` We'll only deploy 1 replica for our simple experiments in this lab environment and this helps to stay within the resource quota of the our lab environment.

* `route`: We create a public route for the IoT Agent API if you want to interact with it from your own computer.

* The `resources:` definition defines the memory and CPU requests and limits for our IoT Agent JSON pod. We have to keep this lower than for a production deployment because this lab usesa shared smrt cities platform for running Smart Village services. 

For more information about the IoTAgentJson custom resource definition, link:https://github.com/smartabyar-smartvillage/smartvillage-operator/blob/main/config/crd/bases/smartvillage.computate.org_iotagentjsons.yaml[see the full IoTAgentJson schema here].

As note, many of the smart village platform components are already deployed for you, but run these command in your showroom terminal to check and confirm.

TIP: Check that you are in the right project and logged in via the showroom terminal. 

----
oc whoami
oc project
oc get pod -l app.kubernetes.io/instance=iotagent-json
oc wait pod -l app.kubernetes.io/instance=iotagent-json --for=condition=Ready --timeout=2m
oc get pod -l app.kubernetes.io/instance=iotagent-json

----

== Registering your smart devices with the agent

In the last exercise, you found and created some smart devices, and hopefully these included

* at least one *traffic light* which you should have saved the geojson encoding for
* at least one *traffic light observed* which you should have saved the geojson encoding for

We will create these corresponding objects and register these with our shared environment now.

=== Register your `SmartTrafficLight` (s)

BY using the CRDs in the last lab, the smart village operator has already registered these devices for you. Note however, that these devices are listening to and connected to our shared smart village operator instance and not your own.

----
oc get SmartTrafficLight
----

=== Register your `TrafficFlowObserved` (s) -- aka your Traffic Cameras

----
oc get TrafficFlowObserved
----

=== Register your `CrowdFlowObserved` (s)

----
oc get CrowdFlowObserved
----
== The role of Context information

While we were created these objects, lets take a moment to look a little more closely as what we are creating.

If you recall back to an earlier lab, notice in particular potions of the object definitions such as 


----
 ngsi_ld:
    service: trafficflowobserveds
    service_path: /Sweden/Veberod/CityCenter
    context: https://raw.githubusercontent.com/computate-org/smartabyar-smartvillage-static/main/fiware/context.jsonld
----

Taking a look at this data in more detail, execute this in your showroom terminal:

----
curl https://raw.githubusercontent.com/computate-org/smartabyar-smartvillage-static/main/fiware/context.jsonld
----

You should see there are a number entries provided in this object

----
    "customMaxGreenTime" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficFlowObserved/attributes/customMaxGreenTime.md",
    "customAverageVehiclesPerMinute" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficFlowObserved/attributes/customAverageVehiclesPerMinute.md",
    "customDemandScalingFactor" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficFlowObserved/attributes/customDemandScalingFactor.md",
    "customQueueLengthThreshold" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficFlowObserved/attributes/customQueueLengthThreshold.md",
    "TrafficSimulation" : "smartvillage:TrafficSimulation",
    "startDateTime" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/startDateTime.md",
    "simulationName" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/simulationName.md",
    "fcdFilePath" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/fcdFilePath.md",
    "netFilePath" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/netFilePath.md",
    "startSeconds" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/startSeconds.md",
    "endSeconds" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/endSeconds.md",
    "stepSeconds" : "https://github.com/computate-org/smartabyar-smartvillage-static/blob/main/fiware/TrafficSimulation/attributes/stepSeconds.md",
----

Each is a *reference* to the type of contextual data that the encapsulating object may be related to and the data model that describes the relationship. However, it does not specify a specific instance of each contextual data -- it is up an application in use to check for the presence  of potentially relevant contextual data -- potentially retrieving entity specific information from a context broker.

For example, a the context may be information about the road at the intersection:

----
curl https://smart-data-models.github.io/dataModel.Transportation/Road/examples/example.jsonld
----

You should see something like:
----
{
  "id": "urn:ngsi-ld:Road:Spain-Road-A62",
  "type": "Road",
  "alternateName": "E-80",
  "description": "Autov\u00eda de Castilla",
  "length": 355,
  "name": "A-62",
  "refRoadSegment": [
    "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-0-355-forwards",
    "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-0-355-backwards"
  ],
  "responsible": "Ministerio de Fomento - Gobierno de Espa\u00f1a",
  "roadClass": "motorway",
  "@context": [
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
    "https://raw.githubusercontent.com/smart-data-models/dataModel.Transportation/master/context.jsonld"
  ]
}
----

Bringing this data together can have a powerful impact. For example, a street lamp and a bus have two very different contexts, yet if the street lamp “knows” where the bus is, it can switch on as the bus arrives, allowing passengers to see better as they alight. The lamppost could provide direction information, local news and events, and a WiFi hotspot, remaining illuminated until all the passengers have left its coverage zone, switching off to save energy. 

== Your smart city

Congratulations, you have now got your smart devices registered with an agent so that we can communicate with with these devices and collect and use data in the context broker.

What's next?

=== Observing the data you are collecting.

Simulating activity is critical to test improvements and determine what will be effective at achieving your intended goals and cost efficient to implement. Out next labs will start down this process.

=== Analytics & AIML

Analytics derived from smart city data and sensors can significantly enhance the quality of life for citizens in various ways.

The Openshift AI platform that can be  deployed with Openshift Container Platform is a critical enabler of a complete analytic workflow process by allowing these simulations to drive experiments, collect the results, and detect and check for potential errors or biases (which is essential anytime you are working with simulated data) 

=== Other domains

We are focused on traffic scenarios ad that is what these devices provide data for. But smart cities have to leverage a lot of other data types and integrate these. In concert, e NSGI-lD data models and the FIWARE platform encompass many of domains of interest to a smart city manager (thats you!).

