= The smart village microservice

We are writing a Microservice that we can run on openshift. The goal is to read Map data from the official Smart Village API and push map data to your own Smart Village instance that we have deployed in the previous labs.

In this lab, we will be making use of the Openshift AI workbench to create our application that can interact with the smart village components we have already seen and deploy an application that can interact with the smart devices in your smart city.   We will do this by writing a Python program and a Dockerfile that will containerize the service -- Openshift AI already has the python oriented development tools to make this process simple and it lays the foundation for later experimentation.

== Setting values we will use for this program

Before we get started, we will set up a few convenience items that we will use for testing this application, we want to talk to the environment you hav deployed previously notebook. 
The above commands will first set environment variables for `MAP_SERVER_URL`, `CLIENT_ID` and `CLIENT_SECRET` and use them to create a openshift secret we can later download to update our workbench in the next section.


It will ask you to enter your username and password. This is where you enter your GitHub username, and the token value you copied from GitHub earlier. The git credential.helper store should remember your password.

=== Open the course Jupyter Notebook
A Jupyter Notebook is an interactive, online notebook, and the rest of the course be found in the Jupter Notebook. Here is how to find the course Jupyter Notebook.

In your workbench, make sure your left sidebar is open. If it’s not, press [ Ctrl ] + [ b ].
Navigate to smartabyar-smartvillage-sandbox-course.
Open the first Notebook `deploy-python-microservice.ipynb` and follow the instructions from there.

